### ISSUE TITLE
Replace disallowed cold card characters in wallet names with permissible ones

### ISSUE THREAD

**Issue by waldenraines** [unchained-capital/unchained-wallets#48]
Unfortunately cold card truncates the names of multisignature wallets that contain characters it doesn't like.  

We should replace spaces and other "invalid" characters with valid ones so you don't end up with a situation like this:

![img_20201214_142934583](https://user-images.githubusercontent.com/4116405/102157723-ffcd9880-3e4d-11eb-9347-f532dd8f7e46.jpg)

**Comment by humanumbrella** [comment]
This problem is a bug in Coldcard wallet config processing code ... they use `#` as a comment character and truncate the line up to the `#` - but that should only happen if the `#` is the first character on the line.

See -> https://github.com/Coldcard/firmware/blob/master/shared/multisig.py#L543-L549

**Comment by humanumbrella** [comment]
They put a fix in for this one with latest changes after I informed

See -> https://github.com/Coldcard/firmware/blob/master/shared/multisig.py#L555
